security:
    enable_authenticator_manager: true
    encoders:
        Symfony\Component\Security\Core\User\User: 'auto'
#        Symfony\Component\Security\Core\User\User: 'plaintext'

    providers:
        backend_users:
            memory:
                users:
                    user: { password: '$argon2id$v=19$m=65536,t=4,p=1$347NyHku9D1AdeSc9m5fZw$F4J/mrhozHfxFEoBjBTWn6awIVizRReo0EPvJT2Sf2g', roles: [ 'ROLE_USER' ] }
                    admin: { password: '$argon2id$v=19$m=65536,t=4,p=1$QawqbUu28hv4/xkzy5LuFA$gzo72wtiCva9yfKZLPhu4PnKL+2dayKCcS1vYqrcDOU', roles: [ 'ROLE_ADMIN', 'ROLE_USER' ] }


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/api/v1/test/login
            stateless: true
            provider: backend_users
            json_login:
                check_path: /api/v1/test/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/api
            stateless: true
            provider: backend_users
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

        basic:
            pattern: ^/api/v1/basic
            http_basic:
                realm: Access denied

    access_control:
        - { path: ^/api/v1/test/users, roles: ROLE_USER }
        - { path: ^/api/v1/test, roles: ROLE_ADMIN }
