monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: info
            handler: graylog
            channels: ["!event"]

        graylog:
            type: gelf
            publisher:
                hostname: '%env(GRAY_HOST)%'
                port: '%env(GRAY_PORT)%'
            formatter: monolog.formatter.gelf_message

        file:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]

        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]

#monolog:
#    handlers:
#        main:
#            type: stream
#            path: "%kernel.logs_dir%/%kernel.environment%.log"
#            level: debug
#            channels: ["!event"]
#        console:
#            type: console
#            process_psr_3_messages: false
#            channels: ["!event", "!doctrine", "!console"]
